## Gibbs sampler
We're going to try out Gibbs sampling on the hypercube. The simplest possible case surely?

ie. there are $N$ variables, and they're all binary, so there are $2^N$ states, which are the vertices of a hypercube in $N$ dimensions.

We'll specify some probability $P(\mathbf{x})$ for each pattern (= binary string) $\mathbf{x}$.

Then we'll run heaps of Gibbs Sampler updates from some initial state, and count how often the sampler visits each state.

If we're right, these counts should come to match our target distribution: bingo!

In [24]:
%matplotlib inline
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rng
np.set_printoptions(precision = 2, suppress = True)
import time
rng.seed(int(time.time())) # seed the random number generator

In [25]:
# make up an array with each row being one of the binary patterns. Do 'em all.
N = 3
# Oh dear: there are better ways to do this than simply reciting, but it's 3:55pm!
inpats = np.array([[0,0,0], [0,0,1], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,0], [1,1,1]])
print (inpats)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [26]:
# Make up some probability distribution over all the inpats
targetProbs = rng.random(size=(len(inpats),1))
targetProbs = targetProbs / targetProbs.sum()
print (targetProbs)

[[ 0.21]
 [ 0.  ]
 [ 0.03]
 [ 0.2 ]
 [ 0.18]
 [ 0.23]
 [ 0.07]
 [ 0.08]]


## Gibbs goes here

In [27]:
# do it


## compare samples made by Gibbs with the target distribution

In [28]:
# do it, visually if possible.
